
FROM node:20-alpine

# Needed for native modules like bcrypt
RUN apk add --no-cache python3 make g++ 

WORKDIR /app/backend_country

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev"]